mysite/myapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='myapp'
urlpatterns = [
    path('',views.index),
    path('products/',views.products),
    path('products/<int:id>/',views.product_detail,name='product_detail'),
    
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
]

mysite/myapp/models.py
from unicodedata import name
from django.db import models

# Create your models here.
class Product(models.Model):
    def __str__(self):
        return self.name
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    desc = models.CharField(max_length=200)

mysite/myapp/views.py
from multiprocessing import context
from django.shortcuts import render
from django.http import HttpResponse
from .models import Product
# Create your views here.
def index(request):
    return HttpResponse("Hello World ")

def products(request):
    products = Product.objects.all()
    context ={
        'products':products
    }
    return render(request, 'myapp/index.html',context)

def product_detail(request,id): 
    product = Product.objects.get(id=id)
    context = {
        'product':product
    }
    return render(request,'myapp/detail.html',context) 

mysite/myapp/templates/myapp/base.html
<html>
    <head>
        <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
    </head>
    <body>
        
    </body>
</html>

mysite/myapp/templates/myapp/detail.html
This is a detail page for
<h1>{{product.name}}</h1>
<h2>{{product.price}}</h2>
<h3>{{product.desc}}</h3>

mysite/myapp/templates/myapp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
    <title>Document</title>
</head>
<body>
    <nav class="bg-white shadow-lg">
        <div class="max-w-6xl mx-auto px-4">
            <div class="flex justify-between">
                <div class="flex space-x-7">
                    <div >
                        <a href="#" class="flex items-center px-2 py-4">
                        <img class="h-8 w-8" src="{% static 'myapp/images/shopping.png' %}" alt="">
                        <span class="text-lg font-semibold">Buy&Sell</span>

                        </a>
                        
                    </div>
                    <div class="items-center flex space-x-1">
                        <a href="#" class="py-4 px-2 text-gray-500 font-semibold border-b-4 border-green-500">Home</a>
                        <a href="#" class="py-4 px-2 text-gray-500 font-semibold">About</a>
                        <a href="#" class="py-4 px-2 text-gray-500 font-semibold">Contact</a>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <!-- {{products}} -->
    {% for product in products %}
    <a href="{% url 'myapp:product_detail' product.id %}">
   <h2> {{product.name}} </h2>---> {{product.price}} ---> {{product.desc}} <br>
    </a>
    {% endfor %}
</body>
</html>